# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('employer', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=150)),
                ('salary', models.CharField(max_length=30)),
                ('working_place', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=150)),
                ('condition', models.TextField()),
                ('responsibility', models.TextField()),
                ('education', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('requirements', models.TextField()),
            ],
            options={
                'db_table': 'md_vacancy',
            },
        ),
    ]
